[project]
name = "backend"
version = "0.1.0"
description = "Authentication API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "motor>=3.3.2",
    "passlib[bcrypt]>=1.7.4",
    "python-multipart>=0.0.9",
]
